
server:
   port: 8888
spring:
  profiles:
    active: native


  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/,classpath:config/doctorservice,classpath:config/cardservice,classpath:config/appointmentservice
        encrypt:
          enable: false


logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.appointment: INFO