server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10
    jedis:
      pool:
        max-active: 9
        max-wait: -1
        max-idle: 8
        min-idle: 0
