server:
  port: 80


# 做一个类似 security一样的默认登陆页面功能，进一步的理解 Spring Boot 的 默认配置含义及设计思想
#authorization:
#  login:
#    loginPage: /loginDemo.html

spring:
  application:
    name: authorization
  datasource:
    url: jdbc:mysql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:3306}/security
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:zhao-324}
    driver-class-name:  com.mysql.jdbc.Driver
  #配置oauth2过滤的优先级
  oauth2:
    resource:
      filter-order: 3

  redis:
    host: 127.0.0.1
    port: 6379
  security:
    oauth2:
      storeType: jwt
      jwt:
        SigningKey: oauth2
    social:
      qq:
        app-id: 101448999
        app-secret: 1d958787a87559bad371c0a9e26eef61